import 'package:google_generative_ai/google_generative_ai.dart';

class GenerativeAIService {
  late final GenerativeModel _model;

  GenerativeAIService() {
    const apiKey =
        'AIzaSyDYBXv2vO4I1zhQqMcZs_IzRUu7lPL7S3M'; // Replace with your actual Gemini API key
    _model = GenerativeModel(model: 'gemini-1.5-flash', apiKey: apiKey);
  }

  Future<List<Map<String, String>>> generateTasks(String prompt) async {
    final aiPrompt = '''
Generate a list of 5 to-do tasks based on the following prompt: "$prompt". 
Each task should include:
- A title (short, 3-5 words)
- A description (1-2 sentences)
- A due date (in the format "YYYY-MM-DD")
Format the response as a numbered list with the following structure:
1. **Title**: [Task Title], **Description**: [Task Description], **Due Date**: [YYYY-MM-DD]
2. **Title**: [Task Title], **Description**: [Task Description], **Due Date**: [YYYY-MM-DD]
...and so on for all 5 tasks.
''';

    final response = await _model.generateContent([Content.text(aiPrompt)]);

    if (response.text == null) {
      throw Exception('No tasks generated by AI');
    }

    final tasks = <Map<String, String>>[];
    final lines = response.text!
        .split('\n')
        .where((line) => line.trim().isNotEmpty);

    for (var line in lines) {
      final regex = RegExp(
        r'\d+\.\s*\*\*Title\*\*:\s*(.+?),\s*\*\*Description\*\*:\s*(.+?),\s*\*\*Due Date\*\*:\s*(\d{4}-\d{2}-\d{2})',
      );
      final match = regex.firstMatch(line);
      if (match != null) {
        tasks.add({
          'title': match.group(1)!,
          'description': match.group(2)!,
          'dueDate': match.group(3)!,
        });
      }
    }

    if (tasks.isEmpty) {
      throw Exception('Failed to parse AI-generated tasks');
    }

    return tasks;
  }
}
