import 'package:google_generative_ai/google_generative_ai.dart';

class GenerativeAIService {
  late final GenerativeModel _model;

  GenerativeAIService() {
    const apiKey = 'AIzaSyDYBXv2vO4I1zhQqMcZs_IzRUu7lPL7S3M';
    _model = GenerativeModel(model: 'gemini-1.5-flash', apiKey: apiKey);
  }

  Future<List<Map<String, String>>> generateTasks(String prompt) async {
    var date = DateTime.now();
    final aiPrompt = '''
You are tasked with generating a list of to-do tasks based on the following prompt: "$prompt". 
Follow these steps to determine the number of tasks to generate:
1. If the prompt specifies a number of tasks (e.g., "Plan a productive morning with 3 tasks" or "Generate 4 tasks for studying"), extract that number.
   - The number may be written as a digit (e.g., "3 tasks") or a word (e.g., "three tasks").
   - If the number is greater than 10 or less than 1, default to 5 tasks.
2. If the prompt does not specify a number of tasks (e.g., "Plan a productive morning"), default to generating exactly 5 tasks.

Each task must be actionable, relevant to the prompt, and suitable for a personal to-do list. 
Each task should include:
- A title (3-6 words, concise and specific)
- A description (1-3 sentences, 10-35 words, providing clear context or instructions)
- A due date (in the format "YYYY-MM-DD", must be a future date within the next 30 days from "$date" this date)

Format the response as a numbered list with the following structure, ensuring no extra spaces or deviations:
1. **Title**: [Task Title], **Description**: [Task Description], **Due Date**: [YYYY-MM-DD]
2. **Title**: [Task Title], **Description**: [Task Description], **Due Date**: [YYYY-MM-DD]
...and so on for the determined number of tasks.

Examples:
- Prompt: "Plan a productive morning with 3 tasks"
  1. **Title**: Wake Up Early, **Description**: Rise at 6 AM to start your day fresh., **Due Date**: 2025-05-02
  2. **Title**: Morning Run, **Description**: Jog for 30 minutes around the park., **Due Date**: 2025-05-02
  3. **Title**: Healthy Breakfast, **Description**: Prepare oatmeal with fruits for energy., **Due Date**: 2025-05-02

- Prompt: "Plan a productive morning"
  1. **Title**: Wake Up Early, **Description**: Rise at 6 AM to start your day fresh., **Due Date**: 2025-05-02
  2. **Title**: Morning Run, **Description**: Jog for 30 minutes around the park., **Due Date**: 2025-05-02
  3. **Title**: Healthy Breakfast, **Description**: Prepare oatmeal with fruits for energy., **Due Date**: 2025-05-02
  4. **Title**: Review Emails, **Description**: Check and respond to urgent emails., **Due Date**: 2025-05-03
  5. **Title**: Plan Day, **Description**: Outline tasks for a productive day., **Due Date**: 2025-05-03

Ensure the output strictly follows this structure for the determined number of tasks.
''';

    final response = await _model.generateContent([Content.text(aiPrompt)]);

    if (response.text == null) {
      throw Exception('No tasks generated by AI');
    }
    final tasks = <Map<String, String>>[];
    final lines = response.text!
        .split('\n')
        .where((line) => line.trim().isNotEmpty);

    for (var line in lines) {
      final regex = RegExp(
        r'\d+\.\s*\*\*Title\*\*:\s*(.+?),\s*\*\*Description\*\*:\s*(.+?),\s*\*\*Due Date\*\*:\s*(\d{4}-\d{2}-\d{2})',
      );
      final match = regex.firstMatch(line);
      if (match != null) {
        tasks.add({
          'title': match.group(1)!,
          'description': match.group(2)!,
          'dueDate': match.group(3)!,
        });
      }
    }
    if (tasks.isEmpty) {
      throw Exception('Failed to parse AI-generated tasks');
    }

    return tasks;
  }
}
